### ISSUE TITLE
Treat "non-exhaustive case" as warning

### ISSUE THREAD

**Issue by bnnthang** [azdavis/millet#12]
I'm referring to [error 5011](https://github.com/azdavis/millet/blob/main/docs/errors.md#5011). I think we should treat "non-exhaustive case" as a warning instead of an error as the current implementation. Even in SMLNJ this is a warning.

Does the current language server support "warnings" or are there only "errors"?

![image](https://user-images.githubusercontent.com/54808964/192106064-d82e9110-a7c7-4429-92ca-d8dd0db4b45f.png)

![image](https://user-images.githubusercontent.com/54808964/192106097-49a18ea4-bc00-44d0-b544-b8db9903f36c.png)

**Comment by azdavis** [comment]
Millet reports every diagnostic as an error. But, since Millet doesn’t actually run any SML code, this shouldn’t stop you from ignoring the “error” and running your SML with e.g. SML/NJ.

Can you give some more detail about what it is you want to do here? If your intent is to ignore messages about non-exhaustiveness from Millet, you can already do that even when it’s reported as an error.

**Comment by bnnthang** [comment]
What I think is nice to have is to display different levels of "errors" on VSCode. For example, the warnings and informations have different "icons" in the "problems" list as below

![image](https://user-images.githubusercontent.com/54808964/192127602-789e9408-1812-441e-9837-c7781e46c3f1.png)

**Comment by azdavis** [comment]
Here's my opinion:

- If we want to do this, it should be an option for whether to treat it like a warning or error. (It is an option in SML/NJ, defaulting to warn.)
- The option should default to the current behavior (treat it like an error). Newer languages like Rust treat this as an error, which IMO leads to less "warning noise" since it must be addressed to compile. (You can use the `fill case` feature to fill in all the unmatched branches, or just a wildcard: `_`.)
- I'm not sure where the config for this option should be: in the user settings (i.e. `.vscode/settings.json`) or project settings (`millet.toml`). Probably the former.
- This seems like a minor enough feature that I'm not going to prioritize implementing it right now. But feel free to send a patch.

As for the TODO thing, given that TODO is not a SML-specific thing, Millet wouldn't be the right place to implement anything to do with TODO comments. There are extensions which highlight TODO and other comments, like [this one](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight).

**Comment by azdavis** [comment]
v0.3.13 adds the ability to override error severity in `millet.toml` on a by-error-code basis.

Add the following to your millet.toml to set non-exhaustive (case | binding) errors to display as warnings:

```toml
[errors]
5011.severity = "Warning"
5012.severity = "Warning"
```

<img width="695" alt="Screen Shot 2022-10-05 at 12 56 01 AM" src="https://user-images.githubusercontent.com/6496454/194009492-7fddb914-fddd-4bb0-9b09-ba7868d481a3.png">
