### ISSUE TITLE
Feature request: implement function docstring popup

### ISSUE THREAD

**Issue by bnnthang** [azdavis/millet#13]
I notice that currently the language server doesn't support function docstring popups. If we look at other language servers, for example, Java, we see that if the user specifies some comments right on top of the function, when the user hovers over the function name, a popup showing the comments appears.

I think this feature is useful, considering that a lot of users usually write some comments about the function usage.

![image](https://user-images.githubusercontent.com/54808964/192107930-47c3cac0-33ec-4e2b-ac0e-0bf35fb568a6.png)

**Comment by azdavis** [comment]
Millet does support this, you just have to write the comment in a certain way: https://github.com/azdavis/millet/blob/main/docs/manual.md#doc-comments

**Comment by bnnthang** [comment]
Weirdly that doesn't work for me. Do I have to enable something in the extension settings? I'm running VSCode 1.71.2 on Windows and the Millet version is v0.3.10.

Also, I think it is nice if we can define some convention for our docstrings. For example, in the above screenshot, we see that the Java extension uses `@param` to denote the definition of a function parameter.

![image](https://user-images.githubusercontent.com/54808964/192127829-3dd86731-d3c9-4e09-aef4-42b43abd7dfd.png)

**Comment by azdavis** [comment]
Seems like hovering for doc works for everywhere except the def site itself. If you're hovering the def site itself, you have the comment right in front of you anyway, so that seems not too bad.

<img width="212" alt="Screen Shot 2022-09-24 at 10 28 39 PM" src="https://user-images.githubusercontent.com/6496454/192129731-dbb3ebbb-22e6-4069-8fd2-9487d1d59600.png">

As for conventions, 🤷 . You can use whatever style you want, as long as it's Markdown. There are [other existing ML doc comment styles](https://old.reddit.com/r/sml/comments/wttyl3/whats_the_standard_format_of_documentation/), but I just 'invented' one for the purposes of Millet.

**Comment by bnnthang** [comment]
I can work to improve the hovering for the def site if no one plans to do it. It will take me a lot of time since I'm unfamiliar with VSCode API, but this seems low-priority, so I hope it won't matter much.

**Comment by azdavis** [comment]
Closing this since the original issue itself (doc comments) is resolved. If you want to send a patch to implement hover for doc on the def site feel free to.
